version: "3.7"
services:
  app:
    depends_on: 
      - db
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
    image: mysql:5.7
    container_name: travellist-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    networks:
      - travellist

  nginx:
    depends_on: 
      - app
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80    
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - travellist

  scripts:
    depends_on:
      - app
      - db
      - nginx
    image: travellist
    container_name: script_pd
    command: bash -c 'composer install &&
                      php /var/www/artisan migrate --force'  
    volumes:
      - ./:/var/www
    networks:
      - travellist

networks:
  travellist:
    driver: bridge

volumes:
  dbdata:
    driver: local